apiVersion: v1
kind: Service
metadata:
  name: devsu-devops-demo-svc
  namespace: dev1
spec:
  type: LoadBalancer
  selector:
    run: devsu-devops-demo-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
